### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by kennyparsons** [lazymovieguy/BetterRadarrSync#1]
Here is the command I'm running:
```
docker run -ti --rm lazymovieguy/brs:0.1 syncronize http://192.168.2.3 --src-port 7878 --src-profile SyncProfile apikeyredacted http://192.168.2.3 --dest-port 7879 --dest-profile SyncProfile apikey2redacted
```
But I keep getting this error
```
2020-01-13 04:07:35,525 - brs - INFO - Starting Up
Traceback (most recent call last):
  File "/app/brs.py", line 273, in <module>
    BetterRaddarSync()
  File "/app/brs.py", line 163, in __init__
    getattr(self, args.command)()
  File "/app/brs.py", line 227, in syncronize
    'dest_port'], vars(args)['dest-key'])
  File "/app/brs.py", line 84, in __init__
    self.profiles = self._get_profiles()
  File "/app/brs.py", line 141, in _get_profiles
    profiles[profile['name']] = profile['id']
TypeError: string indices must be integers
```

Here are the results of the profile list:
```
docker run -ti --rm lazymovieguy/brs:0.1 profiles http://192.168.2.3 --port 7878 apikeyredacted
```
```
Any,SD,HD-720p,HD-1080p,Ultra-HD,HD - 720p/1080p,Small 1080,SyncProfile
```

Any ideas?

**Comment by lazymovieguy** [comment]
I'll try and look at this, been away for while.
